[package]
name = "keiri_core"
version.workspace = true
edition.workspace = true

[dependencies]
auth.workspace = true
budgets.workspace = true
categories.workspace = true
contacts.workspace = true
db.workspace = true
groups.workspace = true
jobs.workspace = true
ocr.workspace = true
reconciliation.workspace = true
subscriptions.workspace = true

anyhow.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true
better-auth.workspace = true
sea-orm.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
serde_json.workspace = true
transactions.workspace = true
upload.workspace = true
users.workspace = true
wallets.workspace = true
rayon = "1.12.0"
fake = "5.1.0"
chrono.workspace = true
rust_decimal.workspace = true
uuid.workspace = true

[dev-dependencies]
chrono.workspace = true
env_logger = "0.11.10"
migration = { path = "../migration" }
rstest = "0.26.1"
rust_decimal.workspace = true
tracing-test = "0.2.6"
uuid.workspace = true

[lints]
workspace = true

[lib]
doctest = false
test = false
